### ISSUE TITLE
S2 H17 Oppgave 3 del 1

### ISSUE THREAD

**Issue by Annikenothilie** [matematikk/vgs_eksamener#27]
Takk for at du melder fra om feil/forbedringsforslag!
Nedenfor er en mal som du kan velge å bruke.

**Hvor er feilen / forbedringsforslaget?**
S2 H17 del 1, oppgave 3.

**Hva er det som er feil? Hva kan gjøres bedre?**
Oppgaven er skrevet feil ved at den tredje likningen er skrevet som: 2x + y + 2z = 2 
der det i eksamensheftet er skrevet som: 2x + y + z = 2

**Hva burde svaret være?**
Hele likningssystemet blir feil. 
Svaret med korrekte verdier:

1: x + y + 2z = -3
2: x + 3y + z = 2
3: 2x + y + z = 2
------------------
1: x = -3 - y - 2z

2: -3 - y - 2z + 3y + z = 2
                           2y - z = 5

3: 2(-3 - y - 2z) + y + z = 2
       -6 - 2y - 4z + y + z = 2
                            -y - 3z = 8
                                     y = -8 - 3z

2: 2(-8 - 3z) - z = 5
       -16 - 6z - z = 5
                     -7z = 21
                         z = -3

3: y = -8 - 3z = -8 - 3 * (-3) = 1

1: x = -3 - y - 2z = -3 - 1 - 2 * (-3) = 2

Så x = 2, y = 1 og z = - 3.

**Comment by tommyod** [comment]
Hei @Annikenothilie. Takk for at du gir beskjed. Skal fikse dette snarest! :+1:

**Comment by tommyod** [comment]
Da var det fikset. Takk igjen @Annikenothilie !
