### ISSUE TITLE
Feil i oppgave 3c, del 1, våren 17 S2? 

### ISSUE THREAD

**Issue by Ingvildtr** [matematikk/vgs_eksamener#5]
Hei!
Lurer på om det er en feil i fasiten ved oppgave 3c, hvor man skal finne antall ledd vha ABC-formelen.
Det skal vel stå -1 +- 15 og ikke 1+-15? :-)

**Comment by tommyod** [comment]
Hei @Ingvildtr! Takk for kommentar, dette ser feil ut ja.

Jeg har endret filen nå, forskjell finnes [her](https://github.com/matematikk/vgs_eksamener/commit/be6e078d4f054a4da705f149aac0b9dd2a036c00) og den nye filen er [her](https://github.com/matematikk/vgs_eksamener/blob/master/l%C3%B8sningsforslag/S2/S2_17V/S2_17V.pdf).

Gi en lyd dersom du er uenig, og gir gjerne en lyd dersom du finner andre feil. Bra jobba, takk! :+1:
