### ISSUE TITLE
Oppgave 3 c

### ISSUE THREAD

**Issue by XomecStar** [matematikk/vgs_eksamener#6]
mangler negativ fortegn framfor 1 i abc-formelen, ved svare. feil er avmerket med rød boks i vedlagt bilde.

![untitled](https://user-images.githubusercontent.com/39454607/40277066-16683cd6-5c19-11e8-8722-a93cda81ad13.png)

**Comment by tommyod** [comment]
Hei @CoderArrio. Takk for beskjed. Feilen er fikset.
