### ISSUE TITLE
Feil i oppgave 4b del 2 vår 2016 S2

### ISSUE THREAD

**Issue by BASkjeggestad** [matematikk/vgs_eksamener#7]
Hei og takk for dine bidrag på matematikk.net. Gammelt dokument dette, men en elev av meg som øver til eksamen forstod ikke hvorfor hun fikk et annet svar enn deg. Det ser ut til at du har antatt at det settes inn penger på konto på 18årsdagen, men da første innskudd er ved fødsel og det totalt skal være 18 årlige innskudd vil siste innskudd være på 17årsdagen. Mulig avviket forplanter seg videre til c-oppgaven men det har jeg ikke sjekket.

**Comment by tommyod** [comment]
Hei!

Tusen takk for beskjed. Jeg har endret løsningsforslaget og lagt inn en ny mulig endring [her](https://github.com/matematikk/vgs_eksamener/pull/8).

Differanse i filene er [her](https://github.com/matematikk/vgs_eksamener/pull/8/files), og den nye .pdf filen er [her](https://github.com/matematikk/vgs_eksamener/blob/8ebe301326b6233027b5772e14b2a31a540d439e/l%C3%B8sningsforslag/S2/S2_16V/S2_16V_lf.pdf).

Kan du/dere verifisere om dere er enige, eller eventuelt uenige, med den nye løsningen? Så slår jeg inn endringen i prosjektet når dere har bekreftet.

**Comment by tommyod** [comment]
Jeg antok at det så bra ut.
